insults = [
    "if your brain was dynamite, there wouldn’t be enough to blow your hat off.",
    "you are more disappointing than an unsalted pretzel.",
    "your secrets are always safe with me. I never even listen when you tell me them.",
    "I’ll never forget the first time we met. But I’ll keep trying.",
    "hold still. I’m trying to imagine you with personality.",
    "your face makes onions cry.",
    "kill yourself",
    "I’m not insulting you, I’m describing you.",
    "keep rolling your eyes, you might eventually find a brain.",
    "your face is just fine but we’ll have to put a bag over that personality.",
    "you bring everyone so much joy, when you leave the room.",
    "I thought of you today. It reminded me to take out the trash.",
    "you are the human version of period cramps.",
    "you are like a cloud. When you disappear it’s a beautiful day.",
    "I’d rather treat a baby’s diaper rash than have lunch with you.",
    "I love what you’ve done with your hair. How do you get it to come out of your nostrils like that?",
    "you just might be why the middle finger was invented in the first place.",
    "you have miles to go before you reach mediocre.",
    "bye, hope to see you never.",
    "remember that time you were saying that thing I didn’t care about? Yeah… that's now.",
    "I was today years old when I realized I didn’t like you.",
    "wish I had a flip phone so I could slam it shut on your face.",
    "wow, your maker really didn’t waste time giving you a personality, huh?",
    "those teeth look like you could eat an apple through a tennis racquet.",
    "you have an extremely kind face, the kind you throw bricks at.",
    "if I had a face like yours, I'd sue my parents.",
    "I guess you prove that even god makes mistakes sometimes.",
    "you must have been born on a highway because that's where most accidents happen.",
    "some babies were dropped on their heads but you were clearly thrown at a wall.",
    "I'd slap you, but that would be animal abuse.",
    "the last time I saw something like you, I flushed it.",
    "why don't you slip into something more comfortable, like a coma.",
    "all day I thought of you...... I was at the zoo.",
    "you should really carry a plant around with you to replace the oxygen that you waste when you speak.",
    "as an outsider, what do you think of the human race?"
]

compliments = [
    "your positivity is infectious.",
    "you should be so proud of yourself.",
    "you’re amazing!",
    "you’re a true gift to the people in your life.",
    "you’re an incredible friend.",
    "I really appreciate everything that you do.",
    "you inspire me to be a better person.",
    "your passion always motivates me.",
    "your smile makes me smile.",
    "thank you for being such a great person.",
    "the way you carry yourself is truly admirable.",
    "You are such a good listener.",
    "you have a remarkable sense of humor.",
    "thanks for being you!",
    "you set a great example for everyone around you.",
    "I love your perspective on life.",
    "being around you makes everything better.",
    "you always know the right thing to say.",
    "the world would be a better place if more people were like you!",
    "you are one of a kind.",
    "you make me want to be the best version of myself.",
    "you always have the best ideas.",
    "I’m so lucky to have you in my life.",
    "I wish I were more like you.",
    "you are so strong.",
    "I’ve never met someone as kind as you are.",
    "you have such a great heart.",
    "you are beautiful inside and out.",
    "you are so special to everyone you know.",
    "you are my favorite person to talk to.",
    "you’ve accomplished so many incredible things.",
    "I appreciate your friendship more than you can know.",
    "I love how you never compromise on being yourself.",
    "you helped me realize my own worth.",
    "your point of view is so refreshing.",
    "you always make me feel welcome.",
    "you deserve everything you’ve achieved.",
    "I am so proud of your progress.",
    "you are so down to earth.",
    "you know just how to make my day!",
    "you spark so much joy in my life.",
    "your potential is limitless.",
    "you are making a real difference in the world.",
    "you’re so unique.",
    "you are wise beyond your years.",
    "you’re worthy of all the good things that come to you.",
    "your parents must be so proud.",
    "never stop being you!",
    "no one makes me laugh harder than you do.",
    "you continue to impress me.",
    "you make the small things count.",
    "you’re a constant reminder that people can be good.",
    "I admire the way that you challenge me.",
    "you make me see things in an entirely new way.",
    "thanks for always being there for me.",
    "you are a ray of sunshine.",
    "on a scale of one to ten, you’re an eleven.",
    "you would be a cool frog",
    "you’re incredibly thoughtful.",
    "you have the best ideas.",
    "you’re the most perfect ‘you’ there is.",
    "you are the epitome of a good person.",
    "you always know how to find the silver lining.",
    "you’re the person that everyone wants on their team.",
    "I always learn so much when I’m around you.",
    "Is there anything you can’t do!?"

]
